site_name: IBM Business Automation and Digital Labor - Jam-in-a-Box
site_url: https://mydomain.org/mysite
repo_url: https://github.com/IBM/cp4ba-jam-in-a-box
repo_name: BA&DL-JiaB

markdown_extensions:
  - admonition

nav:
  - 'Start': 'index.md'
  - 'Tracks & Capabilities Overview': 'Additional.md'
  - 'Labs':
    - 'IBM Cloud Pak for Business Automation Demo': 'IBM Cloud Pak for Business Automation (End-to-End)\README.md'
    - 'IBM Business Automation Application' : 'Business Automation Application\README.md'
    - 'IBM Automation Decision Services' : 'Decisions\README.md'
    - 'IBM Automation Document Processing': 'Document Processing\README.md'
    - 'IBM Business Automation Insights' : 'Business Automation Insights\README.md'
    - 'IBM Business Automation Workflow': 'Workflow\README.md'
    - 'IBM FileNet Content Manager' : 'Content\README.md'
    - 'IBM watsonx Orchestrate': 'watsonx Orchestrate\README.md'
    - 'IBM Process Mining': 'Process Mining\README.md'
    - 'IBM Robotic Process Automation': 'Robotic Process Automation\README.md'
    - 'Bring-up Lab':
      - 'Home': 'Bring-up\README.md'
      - 'Bring-up Lab 1':
        - 'Rapid Deployment Scripts': 'Bring-up\Bring-Up-Lab-1\README.md'
        - 'Prepare': 'Bring-up\Bring-Up-Lab-1\Exercise-1-Prepare.md'
        - 'Deploy DB2': 'Bring-up\Bring-Up-Lab-1\Exercise-2-Deploy-DB2.md'
        - 'Create DB2 Databases': 'Bring-up\Bring-Up-Lab-1\Exercise-3-Create-DB2-Databases.md'
        - 'Deploy CP4BA Operator': 'Bring-up\Bring-Up-Lab-1\Exercise-4-Deploy-CP4BA-Operator.md'
        - 'Deploy CP4BA': 'Bring-up\Bring-Up-Lab-1\Exercise-5-Deploy-CP4BA.md'
      - 'Bring-up Lab 2':
        - 'Regular Deployment Scripts': 'Bring-up\Bring-Up-Lab-2\README.md'
        - 'Deployment Operator': 'Bring-up\Bring-Up-Lab-2\Exercise-2-Deploy-Operator.md'
        - 'Prepare': 'Bring-up\Bring-Up-Lab-2\Exercise-1-Prepare.md'
        - 'Prepare Deployment': 'Bring-up\Bring-Up-Lab-2\Exercise-3-Prepare-Deployment.md'
        - 'Deploy PostgreSQL': 'Bring-up\Bring-Up-Lab-2\Exercise-4-Deploy-PostgreSQL.md'
        - 'Configure LDAP': 'Bring-up\Bring-Up-Lab-2\Exercise-5-Configure-LDAP.md'
        - 'Generating DBs': 'Bring-up\Bring-Up-Lab-2\Exercise-6-Generating-DBs.md'
        - 'Deploy CP4BA': 'Bring-up\Bring-Up-Lab-2\Exercise-7-Deploy-CP4BA.md'
        - 'Post Deployment': 'Bring-up\Bring-Up-Lab-2\Exercise-8-PostDeployment.md'
        - 'Appendix': 'Bring-up\Bring-Up-Lab-2\Appendinx-A-Troubleshooting.md'
  - 'CP4BA Environment Options':
    - 'Single User Environment CP4BA 23.0.2': 'Solutions\Client Onboarding\README.md'
    - 'ApolloBA CP4BA 23.0.2': 'Solutions\Client Onboarding\README_2302_ApolloBA_CP4BADemos.md'
    - 'Self-deploy scenario to CP4BA 23.0.2': 'Solutions\Client Onboarding\README_2302_SelfDeploy.md'
  

theme:
  custom_dir: custom/
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - content.code.copy
  name: material
  palette:
    # Palette toggle for light mode
    
    - scheme: default
      primary: indigo
      accent: black
      toggle: 
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
